# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main

stages:
  - stage: InstallAndBuild
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true

          - bash: |
              set -x
              curl --location --request POST 'https://api.github.com/repos/azure-sdk/azure-sdk-for-js-pr/branches/sdkAuto/6859/@azure_arm-databricks/rename' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header "Authorization: Bearer ${TOKEN}" \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "new_name": "deprecated/6859/@azure_arm-databricks"
                }'

            displayName: 'Close and Delete'
            env:
              TOKEN: $(azuresdk-github-pat)
