# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main

stages:
  - stage: InstallAndBuild
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true

          - bash: |
              set -x
              curl --location --request PATCH 'https://api.github.com/repos/azure-sdk/azure-sdk-for-go-pr/pulls/2268' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer 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' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "state": "closed"
                }'
              curl --location --request DELETE 'https://api.github.com/repos/azure-sdk/azure-sdk-for-go-pr/git/refs/heads/sdkAuto/6859/armdatabricks' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer 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'

              curl --location --request PATCH 'https://api.github.com/repos/azure-sdk/azure-sdk-for-python-pr/pulls/1262' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer 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' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "state": "closed"
                }'
              curl --location --request DELETE 'https://api.github.com/repos/azure-sdk/azure-sdk-for-python-pr/git/refs/heads/sdkAuto/6859/track2_azure-mgmt-databricks' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer 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'

              curl --location --request PATCH 'https://api.github.com/repos/azure-sdk/azure-sdk-for-go-pr/pulls/2269' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer 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' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "state": "closed"
                }'
              curl --location --request DELETE 'https://api.github.com/repos/azure-sdk/azure-sdk-for-go-pr/git/refs/heads/sdkAuto/6859/databricks_mgmt/2018-04-01/databricks' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer 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'

              curl --location --request PATCH 'https://api.github.com/repos/azure-sdk/azure-sdk-for-js-pr/pulls/995' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer 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' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "state": "closed"
                }'
              curl --location --request DELETE 'https://api.github.com/repos/azure-sdk/azure-sdk-for-js-pr/git/refs/heads/sdkAuto/6859/@azure_arm-databricks' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer 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'

            displayName: 'Close and Delete'
